apiVersion: v1
kind: ReplicationController
metadata:
 name: backend-rc-v4
 labels: 
  group: backend-rc-v2
spec:
 template:
  metadata:
   name: backend-pod
   labels: 
    group: backend
    group: middleware
  spec:
   containers:
    - name: myapp
      image: nginx:latest
